from __future__ import annotations

"""
Validation utilities to keep Phase 1/2 guard rails in place.

Checks performed:
- Placeholder tokens remain in tracked manifests/generators.
- Critical system tasks exist (package repair, repair all); if not, stubs are created.
"""

import argparse
import sys
from pathlib import Path
from textwrap import dedent

PLACEHOLDER_TARGETS = [
    Path("menus/menu.yml"),
    Path("tools/generate_menus.py"),
    Path("SystemToolkit/AdminTools/AutoMenu.ps1"),
]

SYSTEM_TOOL_FILE = Path("system_tool/system_tools.py")
STUB_FILE = Path("system_tool/stubs_phase2.py")
REQUIRED_TASKS = ["package_repair", "scan_and_repair"]


def check_placeholders() -> None:
    missing: list[str] = []
    for path in PLACEHOLDER_TARGETS:
        if not path.exists():
            missing.append(f"{path} (missing file)")
            continue
        text = path.read_text(encoding="utf-8")
        if "PLACEHOLDER" not in text:
            missing.append(str(path))
    if missing:
        raise SystemExit(f"[validate_tools] PLACEHOLDER token missing in: {', '.join(missing)}")
    print("[validate_tools] PLACEHOLDER tokens verified.")


def ensure_system_tasks(create_stubs: bool = True) -> None:
    if not SYSTEM_TOOL_FILE.exists():
        if create_stubs:
            _write_stub_module(REQUIRED_TASKS)
        raise SystemExit(f"[validate_tools] Missing file: {SYSTEM_TOOL_FILE}")

    text = SYSTEM_TOOL_FILE.read_text(encoding="utf-8")
    missing = [name for name in REQUIRED_TASKS if f"def {name}" not in text]
    if missing and create_stubs:
        print(f"[validate_tools] Missing system tasks {missing}. Writing stubs.")
        _write_stub_module(missing)
    elif missing:
        raise SystemExit(f"[validate_tools] Missing system tasks: {', '.join(missing)}")
    else:
        print("[validate_tools] Required system tasks present.")


def _write_stub_module(functions: list[str]) -> None:
    STUB_FILE.parent.mkdir(parents=True, exist_ok=True)
    body = "\n\n".join(
        dedent(
            f"""\
            def {name}(*args, **kwargs):
                \"\"\"Auto-generated stub to satisfy validation; replace with real implementation.\"\"\"
                raise NotImplementedError("Stub for {name} - implement system_tool.system_tools.{name}")
            """
        )
        for name in functions
    )
    STUB_FILE.write_text(
        "# Auto-generated by tools/validate_tools.py to keep validation stable.\n"
        "# Do not rely on these implementations in production; replace with real functions.\n\n"
        f"{body}\n",
        encoding="utf-8",
    )


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Phase 2 validation helpers.")
    parser.add_argument("--check-placeholders", action="store_true", help="Verify PLACEHOLDER tokens remain.")
    parser.add_argument("--ensure-system-tasks", action="store_true", help="Ensure core system tasks exist (creates stubs if missing).")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv or sys.argv[1:])

    if not args.check_placeholders and not args.ensure_system_tasks:
        print("[validate_tools] No actions specified. Use --help for options.")
        return

    if args.check_placeholders:
        check_placeholders()
    if args.ensure_system_tasks:
        ensure_system_tasks(create_stubs=True)


if __name__ == "__main__":
    main()
